const statuses = ['جديد', 'قيد المراجعة', 'قيد التنفيذ', 'مكتمل', 'ملغى'];
document.querySelector('#contractsTable').closest('table').querySelectorAll('th')[3].textContent = 'قناة الدفع';
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[char]));
const date = (value) => value ? new Date(value).toLocaleDateString('ar-SA') : '—';
let adminToken = sessionStorage.getItem('intlakahAdminToken') || window.prompt('أدخل رمز الإدارة (الافتراضي المحلي: dev-local-admin)');
if (adminToken) sessionStorage.setItem('intlakahAdminToken', adminToken);
const apiOptions = { headers: { 'x-admin-token': adminToken || '' } };
async function loadDashboard() {
  const [customersResponse, leadsResponse, contractsResponse, siteOrdersResponse] = await Promise.all([
    fetch('/api/customers', apiOptions), fetch('/api/leads', apiOptions), fetch('/api/contracts', apiOptions), fetch('/api/site-orders', apiOptions)
  ]);
  if ([customersResponse, leadsResponse, contractsResponse, siteOrdersResponse].some((response) => response.status === 401)) throw new Error('unauthorized');
  const [customers, leads, contracts, siteOrders] = await Promise.all([customersResponse.json(), leadsResponse.json(), contractsResponse.json(), siteOrdersResponse.json()]);
  document.getElementById('customerCount').textContent = customers.length;
  document.getElementById('leadCount').textContent = leads.length;
  document.getElementById('contractCount').textContent = contracts.length;
  document.getElementById('siteOrderCount').textContent = siteOrders.length;
  document.getElementById('newCount').textContent = contracts.filter((item) => item.status === 'جديد').length + siteOrders.filter((item) => item.status === 'جديد').length;
  document.getElementById('customersTable').innerHTML = customers.length ? customers.map((item) => `<tr><td dir="ltr">${esc(item.customerCode)}</td><td>${esc(item.name)}</td><td dir="ltr">${esc(item.phone)}</td><td>${date(item.createdAt)}</td></tr>`).join('') : '<tr><td colspan="4">لا يوجد عملاء مسجلون بعد.</td></tr>';
  document.getElementById('leadsTable').innerHTML = leads.length ? leads.map((item) => `<tr><td>${esc(item.name)}</td><td dir="ltr">${esc(item.contact)}</td><td>${date(item.createdAt)}</td><td><span class="status-pill">${esc(item.status || 'جديد')}</span></td></tr>`).join('') : '<tr><td colspan="4">لا توجد بيانات عملاء بعد.</td></tr>';
  document.getElementById('siteOrdersTable').innerHTML = siteOrders.length ? siteOrders.map((item) => `<tr><td>${esc(item.name)}<br><small dir="ltr">${esc(item.customerCode || '—')}</small></td><td>${esc(item.projectTitle)}</td><td>${esc(item.startingPrice || '—')}</td><td dir="ltr">${esc(item.contact)}</td><td>${esc((item.features || []).join('، ') || '—')}</td><td>${date(item.createdAt)}</td></tr>`).join('') : '<tr><td colspan="6">لا توجد طلبات مواقع بعد.</td></tr>';
  document.getElementById('contractsTable').innerHTML = contracts.length ? contracts.map((item) => `<tr><td>${esc(item.clientName)}<br><small dir="ltr">${esc(item.customerCode || '—')}</small></td><td>${esc(item.service)}</td><td>${esc(item.price || '—')}</td><td>${esc(item.paymentMethod || '—')}</td><td><select class="status-select" data-id="${esc(item.id)}">${statuses.map((status) => `<option ${status === (item.status || 'جديد') ? 'selected' : ''}>${status}</option>`).join('')}</select></td></tr>`).join('') : '<tr><td colspan="5">لا توجد عقود بعد.</td></tr>';
  document.querySelectorAll('.status-select').forEach((select) => select.addEventListener('change', () => updateStatus(select)));
}
async function updateStatus(select) { select.disabled = true; await fetch(`/api/contracts/${encodeURIComponent(select.dataset.id)}`, { method:'PATCH', headers:{'Content-Type':'application/json', 'x-admin-token':adminToken}, body:JSON.stringify({ status: select.value }) }); select.disabled = false; loadDashboard(); }
document.getElementById('refreshDashboard').addEventListener('click', loadDashboard); loadDashboard().catch((error) => { const msg = error.message === 'unauthorized' ? 'رمز الإدارة غير صحيح. حدّث الصفحة وأعد المحاولة.' : 'تعذر الاتصال بالخادم. شغّل server.js أولًا.'; document.getElementById('leadsTable').innerHTML = `<tr><td colspan="4">${msg}</td></tr>`; document.getElementById('customersTable').innerHTML = `<tr><td colspan="4">${msg}</td></tr>`; });

const toolbar = document.createElement('div');
toolbar.className = 'admin-toolbar';
toolbar.innerHTML = '<label for="adminSearch">بحث سريع</label><input id="adminSearch" type="search" placeholder="ابحث باسم العميل أو الخدمة..." /><button class="button secondary-button" id="exportCustomers" type="button">تصدير المسجلين CSV</button><button class="button secondary-button" id="exportContracts" type="button">تصدير العقود CSV</button><button class="button secondary-button" id="exportLeads" type="button">تصدير العملاء CSV</button>';
document.querySelector('.admin-stats').after(toolbar);
document.getElementById('adminSearch').addEventListener('input', (event) => { const query = event.target.value.trim().toLowerCase(); document.querySelectorAll('#customersTable tr, #leadsTable tr, #siteOrdersTable tr, #contractsTable tr').forEach((row) => { row.hidden = query && !row.textContent.toLowerCase().includes(query); }); });

document.getElementById('exportCustomers').addEventListener('click', async () => { const response = await fetch('/api/customers', apiOptions); if (!response.ok) return; const rows = await response.json(); const csv = ['رقم العميل,الاسم,رقم الجوال,الحالة,تاريخ التسجيل', ...rows.map((item) => [item.customerCode, item.name, item.phone, item.status, item.createdAt].map((value) => `"${String(value ?? '').replaceAll('"', '""')}"`).join(','))].join('\n'); const blob = new Blob(['\ufeff' + csv], { type:'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'intlakah-customers.csv'; link.click(); URL.revokeObjectURL(link.href); });
document.getElementById('exportContracts').addEventListener('click', async () => { const response = await fetch('/api/contracts', apiOptions); if (!response.ok) return; const rows = await response.json(); const csv = ['رقم العميل,العميل,الجوال,الخدمة,القيمة,قناة الدفع,الحالة,رقم التتبع,تاريخ الإنشاء', ...rows.map((item) => [item.customerCode, item.clientName, item.customerPhone, item.service, item.price, item.paymentMethod, item.status, item.trackingCode, item.createdAt].map((value) => `"${String(value ?? '').replaceAll('"', '""')}"`).join(','))].join('\n'); const blob = new Blob(['\ufeff' + csv], { type:'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'intlakah-contracts.csv'; link.click(); URL.revokeObjectURL(link.href); });
document.getElementById('exportLeads').addEventListener('click', async () => { const response = await fetch('/api/leads', apiOptions); if (!response.ok) return; const rows = await response.json(); const csv = ['الاسم,التواصل,الحالة,تاريخ الإنشاء', ...rows.map((item) => [item.name, item.contact, item.status, item.createdAt].map((value) => `"${String(value ?? '').replaceAll('"', '""')}"`).join(','))].join('\n'); const blob = new Blob(['\ufeff' + csv], { type:'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'intlakah-leads.csv'; link.click(); URL.revokeObjectURL(link.href); });
